name: 'olist_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'olist_dbt_project'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  olist_dbt_project:
    bronze:
      +materialized: view
    silver:
      +materialized: table
      +schema: SILVER
    gold:
      +materialized: table
      +schema: GOLD
  tpch-dbt-snowflake:
    bronze:
      +materialized: incremental
      +incremental_strategy: append
      +schema: tpch_bronze
    silver:
      +materialized: incremental
      +incremental_strategy: merge
      +schema: tpch_silver
    gold:
      +materialized: table   # overridden to incremental per-model where needed (see below)
      +schema: tpch_gold
snapshots:
  olist_dbt_project:
    tpch:
      +target_schema: tpch_silver