version: 2

sources:
  - name: bronze
    database: CDCDATASTACK
    schema: BRONZE
    tables:
      - name: RAW_ORDERS
      - name: RAW_ORDER_ITEMS
      - name: RAW_PAYMENTS
      - name: RAW_CUSTOMERS
      - name: RAW_PRODUCTS